version: '3.8'

services:
  # 1. Database Layer (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Web Application Layer (Node.js Express)
  webapp:
    build: ./webapp
    image: ahmedaelhaj/ticket-webapp:v1
    container_name: web_app
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy

  # 3. Web Server Reverse Proxy (Nginx)
  nginx:
    build: ./nginx
    image: ahmedaelhaj/ticket-nginx:v1
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - webapp

volumes:
  postgres_data:
