apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  postgres-password: my_secure_password 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_USER: my_db_user
  POSTGRES_DB: my_application_db
