apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: ahmedaelhaj/ticket-nginx:v1  # Your Docker Hub Image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-public-service
spec:
  type: NodePort  # Exposes your Nginx proxy to the internet
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-proxy
